project_id = "cjkhwaetdfobwjqmxufx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[functions.nylas-webhook]
verify_jwt = false

[functions.nylas-calendars]
verify_jwt = false

[functions.nylas-exchange]
verify_jwt = false
