-- Clients Table
-- Client demographic and insurance information

CREATE TABLE clients (
  id uuid PRIMARY KEY,
  profile_id uuid,
  first_name text,
  last_name text,
  email text,
  phone text,
  date_of_birth date,
  city text,
  state states,
  zip_code text,
  client_age integer,
  client_preferred_name text,
  client_middle_name text,
  client_address text,
  client_gender text,
  client_gender_identity text,
  client_time_zone text,
  client_minor text,
  client_referral_source text,
  client_self_goal text,
  client_status text,
  client_assigned_therapist text,
  client_is_profile_complete text,
  client_diagnosis text[] DEFAULT '{}'::text[],
  
  -- Primary Insurance
  client_insurance_type_primary text,
  client_insurance_company_primary text,
  client_policy_number_primary text,
  client_group_number_primary text,
  client_subscriber_name_primary text,
  client_subscriber_relationship_primary text,
  client_subscriber_dob_primary date,
  client_primary_payer_id text,
  eligibility_status_primary text,
  eligibility_claimmd_id_primary text,
  eligibility_last_checked_primary timestamptz,
  eligibility_response_details_primary_json jsonb,
  eligibility_copay_primary numeric,
  eligibility_deductible_primary numeric,
  eligibility_coinsurance_primary_percent numeric,
  
  -- Secondary Insurance
  client_insurance_type_secondary text,
  client_insurance_company_secondary text,
  client_policy_number_secondary text,
  client_group_number_secondary text,
  client_subscriber_name_secondary text,
  client_subscriber_relationship_secondary text,
  client_subscriber_dob_secondary date,
  client_secondary_payer_id text,
  eligibility_status_secondary text,
  eligibility_claimmd_id_secondary text,
  eligibility_last_checked_secondary timestamptz,
  eligibility_response_details_secondary_json jsonb,
  eligibility_copay_secondary numeric,
  eligibility_deductible_secondary numeric,
  eligibility_coinsurance_secondary_percent numeric,
  
  -- Tertiary Insurance
  client_insurance_type_tertiary text,
  client_insurance_company_tertiary text,
  client_policy_number_tertiary text,
  client_group_number_tertiary text,
  client_subscriber_name_tertiary text,
  client_subscriber_relationship_tertiary text,
  client_subscriber_dob_tertiary date,
  client_tertiary_payer_id text,
  eligibility_status_tertiary text,
  eligibility_claimmd_id_tertiary text,
  eligibility_last_checked_tertiary timestamptz,
  eligibility_response_details_tertiary_json jsonb,
  eligibility_copay_tertiary numeric,
  eligibility_deductible_tertiary numeric,
  eligibility_coinsurance_tertiary_percent numeric,
  
  -- Treatment Planning
  client_planlength text,
  client_treatmentfrequency text,
  client_problem text,
  client_treatmentgoal text,
  client_primaryobjective text,
  client_intervention1 text,
  client_intervention2 text,
  client_secondaryobjective text,
  client_intervention3 text,
  client_intervention4 text,
  client_tertiaryobjective text,
  client_intervention5 text,
  client_intervention6 text,
  client_treatmentplan_startdate date,
  client_nexttreatmentplanupdate date,
  
  -- Clinical Assessment Fields
  client_privatenote text,
  client_medications text,
  client_personsinattendance text,
  client_appearance text,
  client_attitude text,
  client_behavior text,
  client_speech text,
  client_affect text,
  client_mood text,
  client_thoughtprocess text,
  client_perception text,
  client_orientation text,
  client_memoryconcentration text,
  client_insightjudgement text,
  client_substanceabuserisk text,
  client_suicidalideation text,
  client_homicidalideation text,
  client_functioning text,
  client_prognosis text,
  client_progress text,
  client_sessionnarrative text,
  
  -- TRICARE Specific Fields
  client_tricare_beneficiary_category text,
  client_tricare_sponsor_name text,
  client_tricare_sponsor_branch text,
  client_tricare_sponsor_id text,
  client_tricare_plan text,
  client_tricare_region text,
  client_tricare_policy_id text,
  client_tricare_has_referral text,
  client_tricare_referral_number text,
  
  -- Military/VA Fields
  client_champva text,
  client_relationship text,
  client_vacoverage text,
  client_branchOS text,
  client_recentdischarge text,
  client_disabilityrating text,
  client_currentsymptoms text,
  
  -- System Fields
  client_temppassword text,
  stripe_customer_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE UNIQUE INDEX clients_pkey ON clients USING btree (id);
CREATE INDEX idx_clients_email ON clients USING btree (email);
CREATE INDEX idx_clients_profile_id ON clients USING btree (profile_id);