-- CMS1500_claims Table
-- Medical billing claims table for CMS-1500 forms

CREATE TABLE "CMS1500_claims" (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id uuid,
  claim_md_batch_id text,
  claim_md_id text,
  status text,
  last_submission timestamptz,
  last_status_check timestamptz,
  response_json jsonb,
  remote_claimid text NOT NULL,
  pcn text NOT NULL,
  pat_name_f text NOT NULL,
  pat_name_l text NOT NULL,
  pat_dob date NOT NULL,
  pat_sex char(1) NOT NULL,
  pat_addr_1 text NOT NULL,
  pat_city text NOT NULL,
  pat_state char(2) NOT NULL,
  pat_zip text NOT NULL,
  ins_name_f text NOT NULL,
  ins_name_l text NOT NULL,
  ins_dob date NOT NULL,
  pat_rel char(2) NOT NULL,
  ins_number text NOT NULL,
  ins_group text,
  ins_addr_1 text NOT NULL,
  ins_city text NOT NULL,
  ins_state char(1) NOT NULL,
  ins_zip text NOT NULL,
  payerid text NOT NULL,
  bill_taxid text NOT NULL,
  bill_taxid_type char(1) NOT NULL,
  bill_npi text NOT NULL,
  bill_name text NOT NULL,
  bill_taxonomy text NOT NULL,
  bill_addr_1 text NOT NULL,
  bill_addr_2 text,
  bill_city text NOT NULL,
  bill_state char(1) NOT NULL,
  bill_zip text NOT NULL,
  prov_npi text NOT NULL,
  prov_name_f text NOT NULL,
  prov_name_l text NOT NULL,
  prov_taxonomy text,
  from_date date NOT NULL,
  thru_date date NOT NULL,
  place_of_service char(1) NOT NULL,
  proc_code text NOT NULL,
  mod_1 text,
  mod_2 text,
  mod_3 text,
  mod_4 text,
  diag_ref text NOT NULL,
  units integer NOT NULL DEFAULT 1,
  charge numeric NOT NULL,
  accept_assign char(1) NOT NULL DEFAULT 'Y',
  total_charge numeric NOT NULL,
  diag_1 text,
  diag_2 text,
  diag_3 text,
  diag_4 text,
  diag_5 text,
  diag_6 text,
  diag_7 text,
  diag_8 text,
  diag_9 text,
  diag_10 text,
  diag_11 text,
  diag_12 text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  submission_history jsonb DEFAULT '[]'::jsonb,
  submission_attempts integer DEFAULT 0,
  last_batch_error text,
  batch_status text DEFAULT 'pending'::text
);

-- Indexes
CREATE UNIQUE INDEX claims_pkey ON "CMS1500_claims" USING btree (id);