-- Revert the insurance_accepted table back to its original structure
-- and add the boolean requirement fields to insurance_companies table instead

-- First, revert insurance_accepted table changes
ALTER TABLE public.insurance_accepted 
DROP COLUMN requires_insurance_plan_type,
DROP COLUMN requires_insured_id_number,
DROP COLUMN requires_insured_name,
DROP COLUMN requires_patient_relationship_to_insured,
DROP COLUMN requires_insured_address,
DROP COLUMN requires_insured_date_of_birth,
DROP COLUMN requires_insured_sex,
DROP COLUMN requires_insured_employer_school_name,
DROP COLUMN requires_insurance_plan_program_name,
DROP COLUMN requires_other_insured_name,
DROP COLUMN requires_other_insured_policy_group_number,
DROP COLUMN requires_other_insured_date_of_birth,
DROP COLUMN requires_other_insured_sex,
DROP COLUMN requires_other_insured_employer_school_name,
DROP COLUMN requires_other_insured_plan_program_name,
DROP COLUMN requires_patient_condition_employment,
DROP COLUMN requires_patient_condition_auto_accident,
DROP COLUMN requires_patient_condition_other_accident,
DROP COLUMN requires_health_benefit_plan_indicator,
DROP COLUMN requires_signature_on_file,
DROP COLUMN requires_insured_authorization_payment,
DROP COLUMN requires_group_number,
DROP COLUMN requires_phone_number,
DROP COLUMN requires_website,
DROP COLUMN requires_claims_address_line1,
DROP COLUMN requires_claims_address_line2,
DROP COLUMN requires_claims_city,
DROP COLUMN requires_claims_state,
DROP COLUMN requires_claims_zip,
DROP COLUMN requires_copay_amount,
DROP COLUMN requires_notes;

-- Restore the original insurance_accepted columns
ALTER TABLE public.insurance_accepted 
ADD COLUMN group_number text,
ADD COLUMN phone_number text,
ADD COLUMN website text,
ADD COLUMN claims_address_line1 text,
ADD COLUMN claims_address_line2 text,
ADD COLUMN claims_city text,
ADD COLUMN claims_state text,
ADD COLUMN claims_zip text,
ADD COLUMN copay_amount numeric,
ADD COLUMN notes text;

-- Now add the boolean requirement fields to insurance_companies table as requested
ALTER TABLE public.insurance_companies 
ADD COLUMN requires_insurance_plan_type boolean DEFAULT false,
ADD COLUMN requires_insured_id_number boolean DEFAULT false,
ADD COLUMN requires_insured_name boolean DEFAULT false,
ADD COLUMN requires_patient_relationship_to_insured boolean DEFAULT false,
ADD COLUMN requires_insured_address boolean DEFAULT false,
ADD COLUMN requires_insured_date_of_birth boolean DEFAULT false,
ADD COLUMN requires_insured_sex boolean DEFAULT false,
ADD COLUMN requires_insured_employer_school_name boolean DEFAULT false,
ADD COLUMN requires_insurance_plan_program_name boolean DEFAULT false,
ADD COLUMN requires_other_insured_name boolean DEFAULT false,
ADD COLUMN requires_other_insured_policy_group_number boolean DEFAULT false,
ADD COLUMN requires_other_insured_date_of_birth boolean DEFAULT false,
ADD COLUMN requires_other_insured_sex boolean DEFAULT false,
ADD COLUMN requires_other_insured_employer_school_name boolean DEFAULT false,
ADD COLUMN requires_other_insured_plan_program_name boolean DEFAULT false,
ADD COLUMN requires_patient_condition_employment boolean DEFAULT false,
ADD COLUMN requires_patient_condition_auto_accident boolean DEFAULT false,
ADD COLUMN requires_patient_condition_other_accident boolean DEFAULT false,
ADD COLUMN requires_health_benefit_plan_indicator boolean DEFAULT false,
ADD COLUMN requires_signature_on_file boolean DEFAULT false,
ADD COLUMN requires_insured_authorization_payment boolean DEFAULT false,
ADD COLUMN requires_group_number boolean DEFAULT false,
ADD COLUMN requires_phone_number boolean DEFAULT false,
ADD COLUMN requires_website boolean DEFAULT false,
ADD COLUMN requires_claims_address_line1 boolean DEFAULT false,
ADD COLUMN requires_claims_address_line2 boolean DEFAULT false,
ADD COLUMN requires_claims_city boolean DEFAULT false,
ADD COLUMN requires_claims_state boolean DEFAULT false,
ADD COLUMN requires_claims_zip boolean DEFAULT false,
ADD COLUMN requires_copay_amount boolean DEFAULT false,
ADD COLUMN requires_notes boolean DEFAULT false;