// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjkhwaetdfobwjqmxufx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqa2h3YWV0ZGZvYndqcW14dWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjIxNjYsImV4cCI6MjA2ODY5ODE2Nn0.iWCHu9AXIa_0dgZp_on2UmsGEUyaKZlXWeqqm4mmCdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});